spring.application.name=DemoCheck
spring.datasource.url=jdbc:mysql://172.16.160.121:3306/dummycheck
spring.datasource.username=team4user
spring.datasource.password=team4user

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080