spring.application.name=DemoCheck
spring.datasource.url=jdbc:mysql://192.168.29.77:3306/classicmodels
spring.datasource.username=team4user
spring.datasource.password=team4user


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server.port=8080
#172.16.160.121